### PR TITLE
Add support for React 17

### LINKED ISSUE #558: Should support react 17
https://github.com/Grsmto/simplebar/blob/a0611f7bc31a45970f2f3f645c5f6eee47812f77/packages/simplebar-react/package.json#L39

ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tiddly-git@0.3.6
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   dev react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0" from simplebar-react@3.0.0-beta.10
npm ERR! node_modules/simplebar-react
npm ERR!   dev simplebar-react@"3.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### PR DESCRIPTION
**Pull request by mogzol**
Closes #558 

React 17 introduced [very few breaking changes](https://reactjs.org/blog/2020/08/10/react-v17-rc.htm), and Simplebar works fine on it without any modification.

As mentioned in #558, onScroll event handlers must now be attached to the `scrollableNodeProps` rather than the `<Simplebar>` element itself, because [React 17 no longer bubbles the onScroll event](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#aligning-with-browsers). I didn't fix that problem because it's not really an issue with simplebar, it's just how React 17 works.

### CODE REVIEW

**Comment by alixsep** [comment]
This should not be accepted, you ignored the real issue instead of solving it.

**Comment by mogzol** [comment]
As I mentioned, I don't think it's a real issue. The documentation for Simplebar never claims that attaching an onScroll handler to the base element will fire when the scrollable node scrolls. The only reason it did was because React pre-17 bubbled scroll events. Now that they don't bubble, it makes sense that you have to attach the handler to the actual scrollable node. If you are using onScroll handlers, fixing these issues should be part of your migration to React 17, not (in my opinion) something that Simplebar should work around.

If the project maintainers disagree I'd be happy to update this to make `onScroll` on the `<Simplebar>` element work.

**Comment by abrahammurciano** [comment]
Can this please be merged? @mogzol is right, in that this is not an issue this library should solve. I'd like to use this library for my website, but since I'm using react 17 I can't yet.

**Comment by Grsmto** [comment]
Hi,
Thanks for the clarification. I agree with the statement here. Sorry for the late merge!

**Pull request merged**
