### PR TITLE
add forward ref to react component

### PR DESCRIPTION
**Pull request by abdullaev**
Add forward ref for react component to be able to access scroll element

### CODE REVIEW

**Comment by Demivan** [comment]
This is a breaking change for those who already use refs: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
With this change it would be impossible to get element returned from `getContentElement` without working with DOM directly.
Instead of using ref on scroll element you should be able to use ref on `Simplebar` component and get `SimpleBar` object from DOM element.
To get scroll element use:  `this.simplebarRef.current.SimpleBar.getScrollElement()` and to get content element use `this.simplebarRef.current.SimpleBar.getContentElement()`

**Comment by abdullaev** [comment]
> This is a breaking change for those who already use refs
You can't attach ref to the component at the moment, because it is functional stateless component. 

If forwarding ref is not an option, I think there needs to be class component which holding SimpleBar instance, as you wrote

**Comment by Demivan** [comment]
Or ref should be forwarded to top div

**Comment by Demivan** [comment]
I'm not using React at all, so I don't know what is preferred way of doing it in React. Making it a class sounds good if it does not affect performance.
@Grsmto I would love to have `getScrollElement` and `getContentElement` methods directly on vue component too. Maybe these methods should be added to `Vue` and `React` components? This will make apis the same across frameworks. And because `Vue` component is not a `functional` anyway it will not affect performance there.

**Comment by Demivan** [comment]
@abdullaev Is it possible to do something similar to this https://github.com/Grsmto/simplebar/pull/337 for React component?

**Comment by abdullaev** [comment]
@Demivan yes, I can do it later

**Comment by Grsmto** [comment]
Hey guys,

I have actually been working on this specific need recently on the `next` branch. You should take a look at [this commit](https://github.com/Grsmto/simplebar/commit/042860d175fad56c557f2ae81ca69ef5cd2911b5) it should pretty much do exactly what you guys are talking about.
I tried  to take a more "React-way" approach. It's using a render prop pattern and you can access to 2 refs: `scrollableNodeRef` and `contentNodeRef`. So you don't have to call any imperative API (as you usually try to avoid that in React).

**Comment by abdullaev** [comment]
@Grsmto, nice to hear! :)
So I think I can close PR

**Comment by krachtstefan** [comment]
This sounds great! Any plans on releasing this? 
> Hey guys,
> 
> I have actually been working on this specific need recently on the `next` branch. You should take a look at [this commit](https://github.com/Grsmto/simplebar/commit/042860d175fad56c557f2ae81ca69ef5cd2911b5) it should pretty much do exactly what you guys are talking about.
> I tried to take a more "React-way" approach. It's using a render prop pattern and you can access to 2 refs: `scrollableNodeRef` and `contentNodeRef`. So you don't have to call any imperative API (as you usually try to avoid that in React).

**Comment by Grsmto** [comment]
@krachtstefan glad you want to test that out. I released an alpha version if you want to try it and see if it works for you I would appreciate some feedbacks!
`simplebar-react@1.3.0-alpha.0`

**Comment by krachtstefan** [comment]
I just tried it. I don't use it with react window, but I needed a ref to add a scroll eventlistener to trigger a infinite scroller. Works great!

**Comment by Grsmto** [comment]
Amazing.
I still need to write some documentation for it and then release it.

**Pull request closed without merging**
