### PR TITLE
Allow for lazy initialization

### PR DESCRIPTION
**Pull request by abettadapur**
`recalculate` always causes a reflow. In complex DOM environments, this reflow can be very expensive and delays the initial render of the content.

Introduce an option `lazyInitialization`, which delays the adding of listeners until the next idle callback (or next tick if the browser does not support `requestIdleCallback`). This optimizes the first paint experience

See #371

### CODE REVIEW

**Comment by Grsmto** [comment]
Thanks for this.
What would be the drawbacks of using this option? I suppose you could experience a flash between before/after SimpleBar has finished initialising?

**Comment by abettadapur** [comment]
I actually did not notice any UI flash with this option, even when bumping up the delay to 5000ms to make it really apparent. I can play around with it some more in other environments

**Comment by Grsmto** [comment]
I'm asking this because if there is no drawback, then I don't see a reason to have this as an option and this could be enabled by default.
However if in some scenarios this can have undesired effects yes this makes sense to be an option.

I think if you see a flash that would be on an environment where you don't have floating scrollback (so not on mac OS with floating scrollbars enabled or on mobile devices).

**Comment by abettadapur** [comment]
@Grsmto There is some flashing on Windows. I moved the `hideNativeScrollbars` function outside of the delay. This shouldn't force reflow because we are only writing properties in this function

**Comment by abettadapur** [comment]
I think we should leave it as an option for now in case it breaks someone later. There are a lot of edge cases that I may not have seen

**Pull request closed without merging**
