### PR TITLE
Avoid unnecessary array copies for NodeList iteration

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by andersk** [comment]
Alternatives to `Array.prototype.forEach.call(nodeList, el => {…})` that I considered:

* Modern browsers [support](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) `nodeList.forEach(el => {…})` directly. This could be polyfilled for older browsers by adding `"web.dom.iterable"` to the `include` list of `@babel/preset-env`.
* `for (const el of nodeList) {…}` would be faster, but it ends up being slower after going through Babel. (Also requires `"web.dom.iterable"`.)
* `for (let i = 0; i < nodeList.length; i++) {const el = nodeList[i]; …}` is ugly…I’ve heard it’s significantly faster on some browsers, but not the ones I could easily test.

Also, this CI test that keeps failing seems to be a flaky test on master.

**Comment by Grsmto** [comment]
Actually `preset-env` already adds `web.dom.iterable`, I think due to the `Array.from`. But I was looking into get rid of it to reduce the bundle size (still trying to get rid of most of the polyfills for this reason), so I think your solution is great!

I'll take a look at the test failing on CI.

**Comment by Grsmto** [comment]
Ok I tested locally and tests pass, thanks!

**Comment by Grsmto** [comment]
Ok I tested locally and tests pass, thanks!

**Comment by andersk** [comment]
FWIW, `web.dom.iterable` will no longer be automatically added for `forEach` soon (babel/babel#9449).

**Pull request merged**
