### PR TITLE
added types for simplebar and simplebar-react

### PR DESCRIPTION
**Pull request by vyachsed**

### CODE REVIEW

**Comment by Grsmto** [comment]
Great stuff!
Could you just remove the version change in the package.json? Since this is handled directly by the release tool it doesn't need to be changed manually. Thanks!

**Comment by vyachsed** [comment]
Done)

**Comment by vyachsed** [comment]
Please merge this!

**Comment by vyachsed** [comment]
Thanks! When to expect a new version in npm?

**Pull request merged**
