### PR TITLE
End drag on blur and mouseleave

### PR DESCRIPTION
**Pull request by Juribiyan**
In some cases (like when used in an `<iframe>` or when user swhitches tabs/windows using a keyboard) a scrollbar may stick in "active" state because `mouseup` event occurs outside the `document` scope. Adding `blur` and `mouseleave` events prevents this.

### CODE REVIEW

**Comment by Grsmto** [comment]
Awesome! Thanks for this :) 
I'll take a look!

**Comment by Grsmto** [comment]
Hey, could you tell me on what browse/platform do you experience this issue? I was unable to reproduce by switching window/tab. Thanks!

**Comment by Juribiyan** [comment]
Chrome on Windows. Here's what I do:

1. Open the [homepage](http://grsmto.github.io/simplebar/);
2. Start dragging the slider;
3. Still holding my mouse down, press Ctrl+Tab to switch tab;
4. Release the mouse button;
5. Return to the Simplebar tab;
6. Watch the content scroll as I move my cursor.

I agree this is a weird case but it's more realistic when you put some scrollable content in an `<iframe>`, then  go throgh steps 1–2, then simply release the mouse button outside an iframe, and then hover over the iframe again — the content wil scroll as if you did not release the mouse button.

**Comment by Grsmto** [comment]
Ok thanks I need to test on Windows cause this doesn't seem to happen on mac osx.

**Comment by Grsmto** [comment]
Hey,
I'm happy to merge this but it seems like you did these fix on the v1 and try to push to master which is now v2. I don't know how cause your changes are recent, you probably worked from a quite old version...(your code is using some jQuery functions).
If you can rebase your changes to work on the latest version I can merge that! (otherwise if you don't I'll implement it myself directly).
Thanks!

**Comment by Grsmto** [comment]
I'm closing this until someone reports again this issue, as it's probably outdated. Thanks!

**Pull request closed without merging**
