### PR TITLE
Remove unexpected width: inherit and related rules on [data-simplebar]

### PR DESCRIPTION
**Pull request by andersk**
Fixes: #305

### CODE REVIEW

**Comment by Grsmto** [comment]
I'm not too sure why we have these css rules tbh. I think that I agree with you and removing this would be the best option. We could also have `box-sizing: border-box` that would solve your specific issue but that seems like a hack.

I will do some test see if removing this doesn't break in some scenarios but that would be a good time to do it as it's a breaking change, would work for v4.
Anyway I'll wait until you guys have finisht he integration in Zulip and release v4 once you're happy with it.

**Comment by andersk** [comment]
Cool.

Re: `box-sizing: border-box`, in further support of the “that seems like a hack” sentiment, it wouldn’t solve the corresponding issue in a `width: 50%; position: relative` container, where `width: inherit` decreases the width by a further 50%.

**Comment by andersk** [comment]
@Grsmto 4.0.0-alpha.4 as published is [missing this change](https://cdnjs.cloudflare.com/ajax/libs/simplebar/4.0.0-alpha.4/simplebar.css) even though it’s [in the corresponding Git tag](https://github.com/Grsmto/simplebar/blob/simplebar%404.0.0-alpha.4/packages/simplebar/src/simplebar.css). Did you forget to rebuild `dist` before publishing?

**Comment by Grsmto** [comment]
You are right. I didn't _forget_ since the process is automated but there is a "bug" in the publish process with Lerna.
Funny that this never happened before (or I never noticed!!! :/ ).

**Comment by Grsmto** [comment]
Just published a new version and hopefully fixed the publishing flow issue.
Thanks!

**Comment by andersk** [comment]
I noticed what may still be a publishing flow issue, although I don’t know whether it’s material: the comment at the top of [simplebar.js 4.0.0-alpha.6](https://cdnjs.cloudflare.com/ajax/libs/simplebar/4.0.0-alpha.6/simplebar.js) still reads “SimpleBar.js - v4.0.0-alpha.5”. The comments in alpha.5 and alpha.4 were similarly one version off.

Also, this probably isn’t the cause, but is it intentional that the [`release` script](https://github.com/Grsmto/simplebar/blob/simplebar%404.0.0-alpha.6/package.json#L9) runs `yarn test` *before* `yarn build`?

**Comment by Grsmto** [comment]
Yeah I noticed this as well. 
Lerna release script is really tedious to get right.

> is it intentional that the release script runs yarn test before yarn build?

Yes because if the tests fail then there is no reason to even build. So the script would be stopped directly.
Also the tests are ran from the sources not from the built artifact, if that's what you were implying.

**Pull request merged**
