### PR TITLE
feat: add angular wrapper and example

### PR DESCRIPTION
**Pull request by qiurenbo**
Hi, @Grsmto ,  I have written an Angular wrapper for simplebar in my spare time.

### CODE REVIEW

**Comment by qiurenbo** [comment]
You can see full code [here](https://github.com/qiurenbo/simplebar)

**Comment by Grsmto** [comment]
Hey @qiurenbo thank you for your amazing work!

It seems like the CI is breaking because the node version required by Angular CLI is >= 10.9.0. 
Could you try to change the node version in the `.nvmrc` file?

Once the CI is passing we can merge this!

**Comment by qiurenbo** [comment]
Sorry @Grsmto , I had tried many times but CI still can't pass. It seems like e2e-test timeout problem. Would you give me some help?

**Comment by Grsmto** [comment]
Ok, thanks for your hard work on this.
I will try to take a look at the tests not working on the CI, I remember having a tough time getting them to work for the other packages.

**Comment by Grsmto** [comment]
FYI I will squash your commits into a single one.
We can keep working on fixing the tests on a separate branch/PR so we get this merged right now!

**Comment by Grsmto** [comment]
I gave it a try but I couldn't fix it neither. It's weird the error reported in the CI doesn't really make sense as it breaks some other tests, not the ones from the Angular package.
Also yeah it works just fine locally so I don't get it :/

**Comment by qiurenbo** [comment]
Travis CI run karma and jest-puppeteer test simultaneously will cause this time out error. Maybe it's a matter of Travis CI  insufficient computing resource.:disappointed_relieved:

**Comment by Grsmto** [comment]
@qiurenbo hey, could you give me the access to the npm package? As right now I'm unable to publish `simplebar-angular`as you already published on your account.
My npm account name is:`grsmto`
thanks!

**Comment by aeslinger0** [comment]
Is there a way to recalculate the scrollbar using this? Or does that need to be added to the angular directive yet?

**Comment by Grsmto** [comment]
@aeslinger0 I'm not too sure about this but in theory you shouldn't need to call this function at all.
Could you tell me in what circumstances you have to call it?

**Comment by aeslinger0** [comment]
@Grsmto, I'm using the Angular Material drag and drop CDK to add and remove dom elements. The scrollbar doesn't seem to reflect the content after I drop an element unless I recalculate.

**Pull request merged**
