### PR TITLE
fix(vue) make compatible with vue 2 & 3

### LINKED ISSUE #557: Simplebar + Vue3
**Describe the bug**
`Uncaught TypeError: can't access property "_c", _vm._self is undefined => simplebar-vue.esm.js:38`

**To Reproduce**

1. yarn add simplebar-vue
2. add import simplebar from 'simplebar-vue';
3. add import 'simplebar/dist/simplebar.min.css';
4. add simplebar to components
5. add tag <simplebar></simplebar> around my scolled content
6. start server

**Your environment**

| Software | Version(s) |
| ---------------- | ---------- |
| SimpleBar  | ^1.6.0 |
| Vue | ^3.0.0 |
| Browser | Firefox Developer 87.0b9 (64 bits) |
| Operating System | macOS Big Sur 11.2.3 (20D91) |

### PR DESCRIPTION
**Pull request by MichaelFedora**
I was able to make it compatible with both versions, except for typings. I don't know how to run your tests / they were not able to be run, but it theoretically _should_ work. If you could run them that would be great!

I'm also not entirely sure the typings will work but they _should_.

---

### Changes
- add typings for vue3
- move computed items to ~~data~~ just be assigned in `mounted()` because they don't change and don't need reactivity
- expose recalculate
- add props to be more vue-y
- add type checking
- add docs to props
- update package.json for vue3 whatnot
- (forgot to add to the commit) scroll just directly `$emit`s instead of a weird pass-through
- get attributes via `$attrs` instead of `$refs.element.attributes` or `$el.attributes`

---

Supersedes #578 , closes #557, #600, and #588.

### CODE REVIEW

**Comment by renatodeleao** [comment]
@Grsmto any reason to hold or not reviewing this? I was about to make a [PR myself](https://github.com/Crowd9/simplebar/tree/support-vue-2-and-3), but this covers it and add some extra good stuff namely the props API.

@MichaelFedora if you allow me to review, the only things I would tweak:
- Remove initialisation of the non-reactive [variables in data,](https://github.com/Grsmto/simplebar/pull/609/files#diff-7e4e382411057f3e38db44a6b8eebedd5b8699c6a683b1f1b353b659d3b4737fR117-R123) doing them directly at `mounted()` is enough and that way prevents vue to attach reactive handlers to the objects. It's a minor perf thing
- remove the installation of vue3 and friends as `devDependencies`, that's why tests are failing: if you want to make tests work in vue3 you there's more stuff to do as `@vue/test-utils` has a lot of breaking changes
- Since this is supposed to be cross-compatible, if we want to have both vue2 and 3 tests at the same time there's a bit of work required to make it happen: installing vue3 packages with npm alias, have a `swap-script` like [vuelidate](https://github.com/vuelidate/vuelidate/blob/next/scripts/swap-vue.js), etc. --> [check out this PR for "inspiration" if i may suggest](https://github.com/ndelvalle/v-click-outside/pull/563).

**Comment by MichaelFedora** [comment]
Hey @renatodeleao ! I honestly have no idea what I'm doing with the testing libraries (it's my weakest skill), I simply copied some stuff from #578 . If you want to fork my branch and make your own PR I'll gladly close in favor of yours?

I adjusted the reactive data definitions and added some more type comments. I've tested in Vue2 by using this exact element it in a professional project (along with adding `import 'simplebar/dist/simplebar.min.css';` to it), but that's all I have.

**Comment by Grsmto** [comment]
> @Grsmto any reason to hold or not reviewing this?

Hey @renatodeleao I'm currently on vacations but I'll be able to review this soon. I would be happy to let you review it since I'm not using Vue at all I'm probably not the best person to do it anyway!

**Comment by renatodeleao** [comment]
@Grsmto no problem, enjoy your vacations! 🏖️ 

I'm a bit short on time, but I'll try to squeeze this into the work agenda.

**Comment by anburocky3** [comment]
@renatodeleao Any update on this?

**Comment by MichaelFedora** [comment]
@anburocky3 if you do need this ASAP I do recommend just [copying the file](https://github.com/Grsmto/simplebar/blob/c456dc30dc32c42b5f8b93e481b2152c583fbca3/packages/simplebar-vue/index.vue) and using it locally, it's what I've been doing for the past few months.

**Comment by anburocky3** [comment]
> @anburocky3 if you do need this ASAP I do recommend just [copying the file](https://github.com/Grsmto/simplebar/blob/c456dc30dc32c42b5f8b93e481b2152c583fbca3/packages/simplebar-vue/index.vue) and using it locally, it's what I've been doing for the past few months.

It is using vue2 right? I'm looking for latest vue3.

**Comment by MichaelFedora** [comment]
> 

It should work in both.

**Comment by renatodeleao** [comment]
Folks update: I've patched this PR with isomorphic testing and a couple of fixes to make this work on both vue versions! 
https://github.com/MichaelFedora/simplebar/pull/1

I'm sorry for the delay and the kind of ghosting but life happened and I had a baby 🎉... so didn't have much free time for OSS... neither have now but got some employer sponsor time for this so here it is!

@MichaelFedora didn't push directly to your fork because don't have write access but merge the PR when you can. Then you might have to sync this with `master` and hopefully nothing will break 🤞  — I had some trouble setting up the project because of node versions.

Cheers everyone!

**Comment by MichaelFedora** [comment]
Merged and congratulations @renatodeleao ! 🎉 

The `yarn.lock` might be screwed up but otherwise I was able to get it up-to-date. Might have to abandon testing for it otherwise, as it's such a simple wrapper 😬 oh well.

**Comment by Grsmto** [comment]
Thanks for the work on this! Let me know when you think this is ready for merge and I will happily do it.

**Comment by renatodeleao** [comment]
@MichaelFedora thanks for the merge! 

> The yarn.lock might be screwed up but otherwise I was able to get it up-to-date.

Fetching your branch, and running `yarn` does update `yarn.lock`, so when you have the time please run it and then commit/push the changes to the branch so that @Grsmto can finally merge this. 

When you're at it, one last favour: https://github.com/Grsmto/simplebar/blob/62103fe2951c7d70b9462661b6cad594536fe4ed/package.json#L6-L8

remove these 3 lines, after the `master` sync they're no longer necessary.

> Might have to abandon testing for it

Why? Testing is running fine locally and on CI.

**Comment by MichaelFedora** [comment]
@Grsmto Seems we're good to go!

**Comment by anburocky3** [comment]
@Grsmto When will `next` branch merge into `main` branch?

**Comment by Grsmto** [comment]
This has been release in [simplebar-vue@1.7.0](https://github.com/Grsmto/simplebar/releases/tag/simplebar-vue%401.7.0).

**Comment by MichaelFedora** [comment]
Did something break that caused this to be reverted?

**Comment by renatodeleao** [comment]
Yup, see #630 which is another attempt.

**Pull request merged**
