### PR TITLE
Fix for #67 forceEnabled

### PR DESCRIPTION
**Pull request by webxl**
Simple boolean fix for issue #67

### CODE REVIEW

**Comment by Grsmto** [comment]
Hi webxl,
Thank you very much for your contribution. Still I think I'll have to put this on hold cause this doesn't actually fix the underlying issue behind this. The `forceEnable` doesn't actually display the scrollbar properly from my tests. I couldn't figure out a solution yet so I put this on hold!
I'll let you know when I can merge the PR!

**Comment by webxl** [comment]
Yeah, just noticed that. It looked like a simple fix at first. I got it to work though by reversing this change: https://github.com/Grsmto/simplebar/commit/a11234767139612a62baf65ecd415b5083006b62

Actually, all that is needed to make that change work is "height: 100%". Not sure if that works everywhere though.

**Comment by Grsmto** [comment]
yeah that's it, problem is you'll have infinite headaches testing every possible cases 😅
It was breaking with the absolute positioning on some cases. I should setup a test page with every possible layout scenarios where I encountered issues.
I didn't find a solution yet for the `forceEnabled` that would work on all kind of layout :/

**Comment by webxl** [comment]
Perhaps you can get a free account at Browserstack: https://www.browserstack.com/pricing  The Open Source plan.

Ideally you'd use something like this and check every PR: https://percy.io/ but it's $$$

**Comment by webxl** [comment]
When you said ``forceEnabled`` (with a 'd' at the end?), what browser and OS was that in? All I had to do to get scrollbar to display was add ``data-simplebar-force-enabled="true" `` to the Vertical Scroller demo. I just added another example to the demo with that added.

I also added CSS to hide the browser's scroll bar, but only for webkit.

**Pull request merged**
