### PR TITLE
Use all classes from options

### PR DESCRIPTION
**Pull request by KODerFunk**
Add `horizontal`, `vertical` and `visible` to classNames option

### CODE REVIEW

**Comment by KODerFunk** [comment]
Dear @Grsmto, i cant full-mapping classes when use css-modules.

**Comment by Grsmto** [comment]
Hey man,
This has been PRed already just before you did! https://github.com/Grsmto/simplebar/pull/218

It's now merged and I'll do a release soon with this fix.

**Comment by KODerFunk** [comment]
@Grsmto I use package from branch `next`. I need it! =)))))

**Comment by KODerFunk** [comment]
@Grsmto, man, i need it in `next`-branch. 
https://github.com/Grsmto/simplebar/blob/next/packages/simplebar/src/simplebar.js#L573

**Comment by Grsmto** [comment]
@KODerFunk this has been released already on `simplebar@3.1.0-beta.5`. I don't understand what you are asking. Why do you need it in the `next` branch?

**Pull request closed without merging**
